[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "bonner-libraries"
description = "Assorted Python libraries developed by the Bonner Lab"
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE" }
authors = [{ name = "Raj Magesh Gauthaman", email = "rgautha1@jh.edu" }]
keywords = ["Bonner Lab"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
    "Typing :: Typed",
]
urls = { repository = "https://github.com/BonnerLab/bonner-libraries" }
dependencies = [
    "loguru",
    "tqdm",
    "boto3",
    "numpy",
    "pandas",
    "scipy",
    "mat73",
    "torch",
    "torchvision",
    "xarray[complete]",
    "cf-xarray",
    "netCDF4",
    "dask",
    "nibabel",
    "Pillow",
    "matplotlib",
    "fast-simplification",
    "timm",
    "zenodo-get",
    "osfclient",
]
dynamic = ["version"]

[project.optional-dependencies]
dev = ["ruff", "mypy", "types-requests", "sphinx", "furo"]

[tool.ruff]
target-version = "py313"

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "CPY001",
    "PD013",
    "D103",
    "E302",
    "PLR0913",
    "D203",
    "D212",
    "PD013",
    "PD010",
]
