import numpy as np
import numpy.typing as npt


def derange(
    n: int,
    *,
    n_derangements: int,
    batch_size: int = 1000,
    seed: int = 0,
) -> np.ndarray[int]:
    """Draw distinct derangements of ``range(n)`` — permutations that fix no element.

    Generated by rejection: whole permutations are drawn and those with a fixed point are thrown
    away, so roughly ``1 / e`` of each batch survives and the cost is in draws, not in ``n``.

    The rows come back in lexicographic order, because deduplication sorts them, and the batch
    that satisfies the request usually overshoots it — so the returned set is the lexicographically
    smallest of those drawn, not a uniform sample of the derangements of ``n``. Taking a prefix of
    the result compounds this: a prefix is ordered, not random. Shuffle the rows if the caller
    needs an unbiased subset.

    Args:
    ----
        n: number of elements to derange
        n_derangements: number of distinct derangements to return
        batch_size: permutations drawn per iteration, capped at ``n_derangements``
        seed: seed for the generator, making the result reproducible

    Returns:
    -------
        derangements (n_derangements, n), lexicographically ordered

    """
    rng = np.random.default_rng(seed=seed)

    if batch_size > n_derangements:
        batch_size = n_derangements

    derangements = np.zeros((0, n), dtype=np.uint64)
    while len(derangements) < n_derangements:
        derangements_ = np.stack(
            [rng.permutation(n).astype(np.uint64) for _ in range(batch_size)],
        )
        derangements_ = derangements_[
            ~np.any(derangements_ == np.arange(n, dtype=np.uint64), axis=1),
            ...,
        ]
        derangements = np.concatenate([derangements, derangements_], axis=0)
        derangements = np.unique(derangements, axis=0)

    return derangements[:n_derangements, ...]


def permutation_test(
    samples: np.ndarray,
    null_distribution: np.ndarray,
    tail: str = "both",
) -> npt.NDArray[np.float64]:
    """Compute a permutation p-value for an observed statistic against a null distribution.

    Both the numerator and the denominator are incremented by one, which counts the observed
    statistic as one of its own null draws. That keeps the p-value strictly positive and the test
    valid at small ``n``, where an uncorrected count can report exactly zero.

    The counts are summed over the whole null, so ``samples`` is a single statistic rather than a
    vector of them; the two-sided case compares magnitudes, which assumes a null centred on zero.

    Args:
    ----
        samples: the observed statistic
        null_distribution: statistics recomputed under the null
        tail: ``"left"``, ``"right"``, or ``"both"``

    Returns:
    -------
        the p-value

    """
    n = len(null_distribution)
    match tail:
        case "left":
            p_value = ((samples >= null_distribution).sum() + 1) / (n + 1)
        case "right":
            p_value = ((samples <= null_distribution).sum() + 1) / (n + 1)
        case "both":
            samples = np.abs(samples)
            null_distribution = np.abs(null_distribution)
            p_value = ((samples <= null_distribution).sum() + 1) / (n + 1)
        case _:
            error = "tail must be `left`, `right` or `both`"
            raise ValueError(error)
    return p_value
